### ISSUE TITLE
Crash on Recyclerview - ThreadPost 

### ISSUE THREAD

**Issue by mbatou** [SirriRyisa/cansaCare#7]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eagle.cansacare, PID: 3322
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eagle.cansacare/com.eagle.cansacare.ThreadDisplay}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.database.ValueEventListener com.google.firebase.database.DatabaseReference.addValueEventListener(com.google.firebase.database.ValueEventListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.database.ValueEventListener com.google.firebase.database.DatabaseReference.addValueEventListener(com.google.firebase.database.ValueEventListener)' on a null object reference
        at com.eagle.cansacare.ThreadDisplay.onCreate(ThreadDisplay.java:43)

**Comment by mbatou** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ThreadFragment](https://trello.com/c/2NU6Ibh5/18-threadfragment)

**Comment by mbatou** [comment]
The recycler is displaying the data : content - timeFormatted - liked 

But still not displaying the name of the user.

**Comment by mbatou** [comment]
Fix the recyclerView displaying and the data populating. The new issue is to display the name of the publisher. @SirriRyisa
